# Standalone Staircase Detection Configuration

stair_pointcloud:
  leaf_size: 0.025
  # Cloud Range Cropped for Search (robot-centered bounds)
  min_range_x: -1.0   # 1m backward
  max_range_x:  4.0   # 4m forward
  min_range_y: -3.0   # 3m right
  max_range_y:  3.0   # 3m left
  min_range_z: -2.5   # 2.5m down
  max_range_z:  1.5   # 1.5m up

# Stair Detector Parameters
stair_detector:
  min_stair_count: 3          # Unit: Minimum number of stairs for detection
  stair_slope_min: 0.35       # Unit: Radians
  stair_slope_max: 1.22       # Unit: Radians

  min_stair_width: 0.75       # Unit: Meters # Change this to change the minimum stair width that can be detected

  min_stair_height: 0.08       # Unit: Meters # Change this to change the minimum stair height (rise) that can be detected
  max_stair_height: 0.3      # Unit: Meters # Change this to change the maximum stair height (run) that can be detected
  min_stair_depth: 0.15      # Unit: Meters # Change this to change the minimum stair depth (run) that can be detected
  max_stair_depth: 0.45       # Unit: Meters # Change this to change the maximum stair depth (run) that can be detected

  max_stair_curvature: 0.55   # Unit: Radians # Change this to change maximum staircase curvature for curved staircases

  angle_resolution: 1.0       # Unit: Degrees (For front-view projection)
  robot_height: 1.61           # Unit: Meters (Used to segment ground height)
  initialization_range: 0.5   # Unit: Meters (Range from the ground to search for the initial two steps)
  ground_height_buffer: 0.05  # Unit: Meters (Buffer from robot height where ground lines are classified)
  use_ramp_detection: false    # Eliminates false positives by ensuring lines on ramps are considered, making this false will potentially lead to increased detections at the expense of false positives

# Line Extractor Params
stair_line_extractor:
  # Weighted Line Fitting
  bearing_variance: 0.0001
  range_variance: 0.001
  z_variance: 0.0004
  least_sq_angle_thresh: 0.05
  least_sq_radius_thresh: 0.075

  # Split and Merge Params for Line Detection Node
  max_line_gap: 0.2         # [Unit: Meters]
  min_range: 0.1            # [Unit: Meters]
  max_range: 5.0            # [Unit: Meters]
  min_split_distance: 0.2   # [Unit: Meters]
  min_line_points: 7        # [Unit: Count]
  outlier_distance: 0.2     # [Unit: Meters]